language: python

python:
  - "3.4"

install:
    - pip install jupyter
    - pip install GPy
    - pip install matplotlib
    - pip install numpy
    - pip install scipy
    - pip install sklearn
    - pip install pymc3
    - pip install seaborn

script:
    - jupyter nbconvert --to notebook --execute gaussian_process_regression.ipynb
